### ISSUE TITLE
Stack-overflow for an applicative parse definition

### ISSUE THREAD

**Issue by etorreborre** [markhibberd/pirate#59]
The following two `Parse` trigger a SOE:
```
def some[A](p: Parse[A]) =
  (p |@| many(p))(_ :: _)

def many[A](p: Parse[A]): Parse[List[A]] =
   some(p) ||| nil.pure[Parse]

val f = flag[Int](short('f'), description("a flag"))

Runners.run(List("-f", "1", "-f", "2"), some(f) ~ "command", DefaultPrefs())
```

**Comment by HuwCampbell** [comment]
As mentioned IRL. Not a bug, but a requirement for search to terminate.

**Comment by etorreborre** [comment]
Yep, let's close this.

**Comment by markhibberd** [comment]
@HuwCampbell I am skeptical, there is something amiss here, that means if I use many from scalaz it won't terminate? What is different about this than optparse for example?
